PYD_BCKGR_IMAGE=/home/zoli/project/python/pydun/theme/mixandglass/image/background.jpg
PYD_CAT_DUFO_TPL=/home/zoli/project/python/pydun/theme/mixandglass/template/dune_folder_category_template.txt
PYD_DST_BCKGR_IMAGE="/tmp/pydis/Library/17 Again/background.jpg"
PYD_DST_ICON_IMAGE="/tmp/pydis/Library/17 Again/icon.png"
PYD_DST_THUMB_IMAGE="/tmp/pydis/Library/17 Again/icon_thumb.png"
PYD_ICON_CATEGORY_HEIGHT=233
PYD_ICON_CATEGORY_WIDTH=377
PYD_ICON_DEFAULT=/home/zoli/project/python/pydun/theme/mixandglass/image/icon_default_315x455.png
PYD_ICON_FILE=icon.png
PYD_ICON_HEIGHT=455
PYD_ICON_SCALE_FACTOR=0.85
PYD_ICON_SEL_FILE=icon_sel.png
PYD_ICON_THUMB_FILE=icon_thumb.png
PYD_ICON_USE_SEL=True
PYD_ICON_WIDTH=315
PYD_IMAGE_DIR=/home/zoli/project/python/pydun/theme/mixandglass/image
PYD_LOG_FILE=/tmp/PYDIS.log
PYD_LOGO_IMAGE=/home/zoli/project/python/pydun/theme/mixandglass/image/logo.jpg
PYD_MOV_ACODEC="MP3 / MPA1L3 (енглески)"
PYD_MOV_ACTORS="Зак Ефрон, Leslie Mann, Thomas Lennon, Matthew Perry, Tyler Steelman, Allison Miller, Sterling Knight, Michelle Trachtenberg, Adam Gregory, Hunter Parrish, Zac Efron"
PYD_MOV_ASPECT=2.333:1
PYD_MOV_CERT=PG-13
PYD_MOV_COMPANY="New Line Cinema"
PYD_MOV_COUNTRY=USA
PYD_MOV_DIRECTORS="Burr Steers"
PYD_MOV_FPS=25.0
PYD_MOVIE_DUFO_TPL=/home/zoli/project/python/pydun/theme/mixandglass/template/dune_folder_movie_template.txt
PYD_MOVIESET_DUFO_TPL=/home/zoli/project/python/pydun/theme/mixandglass/template/dune_folder_movieset_template.txt
PYD_MOV_LANG="UNKNOWN, енглески"
PYD_MOV_ORIG_TITLE="17 Again"
PYD_MOV_OUTLINE="About a guy whose life didn't quite turn out how he wanted it to and wishes he could go back to high school and change it. He wakes up one day and is seventeen again and gets the chance to rewrite his life."
PYD_MOV_PLOT="About a guy whose life didn't quite turn out how he wanted it to and wishes he could go back to high school and change it. He wakes up one day and is seventeen again and gets the chance to rewrite his life."
PYD_MOV_QUOTE=
PYD_MOV_RELEASE_DATE=2009-04-14
PYD_MOV_RUNTIME="1h 34m"
PYD_MOV_SUBTITLES=YES
PYD_MOV_TAGLINE="Поново у средњој школи"
PYD_MOV_TITLE="Опет 17"
PYD_MOV_VCODEC=XviD
PYD_MOV_WRITERS="Jason Filardi"
PYD_MOV_YEAR=2009
PYD_OUT_DIR=/tmp/pydis
PYD_SCRIPTS_DIR=/home/zoli/project/python/pydun/theme/mixandglass/script
PYD_SRC_BCKGR_IMAGE="/digital/yamj/Jukebox/17 Again.background.jpg"
PYD_SRC_ICON_IMAGE="/digital/yamj/Jukebox/17 Again.jpg"
PYD_SRC_THUMB_IMAGE="/digital/yamj/Jukebox/17 Again_small.jpg"
PYD_SUBCAT_DUFO_TPL=/home/zoli/project/python/pydun/theme/mixandglass/template/dune_folder_subcategory_template.txt
PYD_THEME_DIR=/home/zoli/project/python/pydun/theme/mixandglass
PYD_TL_DUFO_TPL=/home/zoli/project/python/pydun/theme/mixandglass/template/dune_folder_toplevel_template.txt
PYD_TPL_DIR=/home/zoli/project/python/pydun/theme/mixandglass/template
PYD_TVICON_SCALE_FACTOR=1.0
PYD_TVSET_DUFO_TPL=/home/zoli/project/python/pydun/theme/mixandglass/template/dune_folder_tvset_template.txt
PYD_YAMJ_DIR=/digital/yamj/Jukebox
